### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by jcupitt** [jcupitt/node-vips#1]
Things that need doing before we could declare 1.0, in no order:

- [ ] Documentation
- [ ] Sort out naming conventions: we should probably switch to `newFromFile()`, for example
- [ ] Fix module structure, hide internal things
- [ ] Have something to generate convenience members for `Image`, eg. `Image.black` should be generated automatically.
- [ ] Need convenience functions like `Image.prototype.bandsplit`
- [ ] Enum expansions, eg. `Image.prototype.sin`
- [ ] Need to handle the libvips error buffer
- [ ] Fix up exceptions
- [ ] More arithmetic wrappers need doing by hand, eg. see `Image.prototype.add`
- [ ] Load/save unformatted memory areas, eg. a Buffer holding a uint8 pixel array
- [ ] Load/save formatted memory areas, eg. a string holding a PNG

Please add more!

**Comment by jcupitt** [comment]
More abstract points:

libvips has several ways to make images: `new_from_file`, `new_from_buffer` etc. At the moment these are extra helper functions hanging off the main `Image` constructor, but there's probably a better way.

It's very fragile: `new Image(12);`, for example, will segv immediately. Perhaps there should be some argument checking. 

It ended up mostly being copy-pasted from pyvips, since that was the one I'd done most recently and probably has the best internal structure. That would be a good place to copy-paste docs from, eg.:

https://github.com/jcupitt/pyvips/blob/master/pyvips/vimage.py#L196

https://github.com/jcupitt/pyvips/blob/master/doc/intro.rst

**Comment by jonathan-kosgei** [comment]
Any chance v1 will come out soon? Would you say this is production worthy atm?

**Comment by asilvas** [comment]
It's used to process millions of images daily (that I know of), customer facing. So yes, I'd say it is production worthy.

**Comment by jonathan-kosgei** [comment]
That's okay :) I checked out your package `image-steam` a few days ago and it's pretty cool! I'm trying to build something similar. I'm checking our node-vips for this because sharp doesn't expose all the functionality that vips offers.

**Comment by jcupitt** [comment]
I'm reluctant to declare 1.0 because I'm really not a node programmer -- I'm sure I've done all sorts of horrible things :( 

This package needs someone experienced to look it over and fix it up, or we'll get users who will have to live with ugly stupid stuff that we'll then have to support. Plus the remaining items in this TODO, of course.

**Comment by jonathan-kosgei** [comment]
I totally understand, thank you for the input and the awesome lib! :)
